# Generated by Django 4.1 on 2022-10-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=18)),
                ('father_name', models.CharField(max_length=200)),
            ],
        ),
    ]
