# Generated by Django 4.1 on 2022-10-05 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smpapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('about_me', models.CharField(max_length=200)),
            ],
        ),
    ]
